/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ContentGrid: typeof import('./src/views/Home/components/ContentGrid.vue')['default']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElRow: typeof import('element-plus/es')['ElRow']
    FixedTips: typeof import('./src/views/Home/components/FixedTips.vue')['default']
    FooterFixed: typeof import('./src/views/Home/components/FooterFixed.vue')['default']
    HomePage: typeof import('./src/views/Home/HomePage.vue')['default']
    LogoTitle: typeof import('./src/views/Home/components/LogoTitle.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
