# Copyright (c) 2024 tong<admin>
# 
# This software is released under the MIT License.
# https://opensource.org/licenses/MIT

# build stage
FROM integrated-documents-projects-web:1.0 as build-stage
WORKDIR /app

COPY . .
RUN npm run build:production

# production stage
FROM nginx:stable-alpine as production-stage
# 删除目录下的default.conf文件
RUN rm /etc/nginx/conf.d/default.conf
# 将default.conf复制到/etc/nginx/conf.d/下，用本地的default.conf配置来替换nginx镜像里的默认配置
ADD default.conf /etc/nginx/conf.d
# 将项目根目录下dist文件夹（构建之后才会生成）下的所有文件复制到镜像/usr/share/nginx/html/目录下
COPY --from=build-stage /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]